// Generated by CoffeeScript 1.4.0
(function() {
  var db;

  db = require("../db");

  exports.hello = function(req, res) {
    var name;
    name = req.params.name;
    return res.render("hello", {
      name: name,
      title: name
    });
  };

  exports.news = function(req, res) {
    return db.Article.findAll().success(function(articles) {
      return res.render("articles", {
        articles: articles,
        title: 'blog'
      });
    });
  };

  exports.show = function(req, res) {
    var id;
    id = parseInt(req.params.id);
    return db.Article.find(id).success(function(blog) {
      return res.render("article", {
        article: blog,
        title: blog.title
      });
    });
  };

}).call(this);
