// Generated by CoffeeScript 1.4.0
(function() {

  exports.index = function(req, res) {
    return res.render("index", {
      title: "Fabbook"
    });
  };

  exports.hello = function(req, res) {
    var name;
    name = req.params.name;
    return res.render("hello", {
      name: name,
      title: name
    });
  };

  exports.news = function(req, res) {
    return app.models.Article.findAll().success(function(articles) {
      return res.render("articles", {
        articles: articles,
        title: 'blog'
      });
    });
  };

}).call(this);
